### ISSUE TITLE
It looks like the Release artifact contains too many files

### ISSUE THREAD

**Issue by u3r** [DesperatePeter/starsector-advanced-weapon-control#21]
Hi Peter, 

thanks for that amazing mod - the default AI has been driving me nuts with PD weapons never shooting the important stuff!

Wondering about the huge release zip I noticed 
a) The `jars` folder containing seemingly old versions of the mod (and source-jars)
b) The `Lib` folder containing test-(only) dependencies
c) another `src` folder containing yet another instance of the source files.

Since you already link to the github with all the code - the release could probably be shrunk to 1MB from 4.6

**Comment by DesperatePeter** [comment]
Hi @u3r!
Yeah, there is definitely potential for optimization here.
To be completely honest, I pretty much just used the default release workflow that comes from the template repository I used and never looked at it again.
The jars folder containing a source-jar is intended and meant for people who want to use the mod as a library (as it contains a library for making in-combat GUIs). That way people can navigate the source-code in their IDE. From my (very limited) understanding of how importing libraries in gradle works, including old versions of the jar is so that gradle-style imports (cf. https://github.com/DesperatePeter/test-combat-gui-lib/blob/master/build.gradle.kts#L69) don't brick when I release a new version. But it is very possible that this is not a sensible way of doing things xD
But removing the Lib and src folders from the release is definitely a sensible and easy-to-do thing, so I'll do that for the next release.
Thanks for pointing this issue out!

**Comment by DesperatePeter** [comment]
After doing some research on the topic I think that I concluded that it indeed doesn't make too much sense to include older versions. So I think I'll simply delete old jars from now on.
I'll close this issue with this comment.
If you feel like I failed to address something in the next release, please feel free to open a new issue!
Thanks for bringing it up!
